development:
  adapter: postgresql
  encoding: unicode
  database: flirt_development
  pool: 5
  username: nblanchet
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: flirt_test
  pool: 5
  username: nblanchet
  password:


production:
  adapter: postgresql
  encoding: unicode
  database: flirt_production
  pool: 5
  username: nblanchet
  password:
